apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-mariadb
  namespace: nextcloud
  labels:
    app: nextcloud
spec:
  selector:
    matchLabels:
      app: nextcloud
      tier: mariadb-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nextcloud
        tier: mariadb-backend
    spec:
      containers:
      - image: docker.io/library/mariadb:10.5
        name: nextcloud-mariadb
        args:
        - "--transaction-isolation=READ-COMMITTED"
        - "--binlog-format=ROW"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-mariadb-secret
              key: RootPassword
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-mariadb-secret
              key: DatabasePassword
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: DatabaseUser
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: DatabaseName
        ports:
        - containerPort: 3306
          name: mariadb
        volumeMounts:
        - name: mariadb-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-persistent-storage
        persistentVolumeClaim:
          claimName: nextcloud-mariadb-pv-claim
