apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-nginx
  namespace: nextcloud
  labels:
    app: nextcloud
spec:
  selector:
    matchLabels:
      app: nextcloud
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nextcloud
        tier: frontend
    spec:
      containers:
      - image: docker.io/library/nginx:alpine
        name: nextcloud-nginx
        ports:
        - containerPort: 80
          name: nginx
        volumeMounts:
        - name: configs
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nextcloud-html-storage
          mountPath: /var/www/html
        - name: nextcloud-persistent-storage
          mountPath: /var/www/html/data
        - name: configs
          mountPath: /var/www/html/config/proxy.config.php
          subPath: proxy.config.php
        - name: configs
          mountPath: /var/www/html/config/smtp.config.php
          subPath: smtp.config.php
        - name: configs
          mountPath: /var/www/html/config/onlyoffice.config.php
          subPath: onlyoffice.config.php
        - name: configs
          mountPath: /var/www/html/config/extra.config.php
          subPath: extra.config.php
      volumes:
      - name: nextcloud-html-storage
        persistentVolumeClaim:
          claimName: nextcloud-html-pv-claim
      - name: nextcloud-persistent-storage
        persistentVolumeClaim:
          claimName: nextcloud-pv-claim
      - name: configs
        configMap:
          name: nextcloud-fpm