apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-onlyoffice
  namespace: nextcloud
  labels:
    app: nextcloud
    tier: onlyoffice-backend
spec:
  selector:
    matchLabels:
      app: nextcloud
      tier: onlyoffice-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nextcloud
        tier: onlyoffice-backend
    spec:
      containers:
      - image: docker.io/onlyoffice/documentserver:latest
        name: nextcloud-nginx
        ports:
        - containerPort: 80
          name: onlyoffice
        env:
          - name: JWT_ENABLED
            value: "true"
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: nextcloud-onlyoffice-secret
                key: secret
          - name: JWT_HEADER
            valueFrom:
              secretKeyRef:
                name: nextcloud-onlyoffice-secret
                key: header