apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: nextcloud-mariadb-secret
  namespace: nextcloud
  labels:
    app: nextcloud
    tier: mariadb-backend
data:
  RootPassword: YjkyNmZmZWFkZDM1NDk5NjA1MGZkMjY4NWM5MjU5YzI=
  DatabasePassword: ZmY4MTUxOTlhOTczOGYyNmVmZWVlMWUwZGU4ZjY1YzM=
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: nextcloud-redis-secret
  namespace: nextcloud
  labels:
    app: nextcloud
    tier: redis-backend
data:
  Password: YzY4YjRlMmE3NDU5N2U4NGFmNmQ5MmRlYTQ0YThhNTA=
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: nextcloud-secret
  namespace: nextcloud
  labels:
    app: nextcloud
    tier: fpm-backend
data:
  Domain: bmV4dGNsb3VkLm15ZG9tYWluLmNvbSxuZXh0Y2xvdWQubmV4dGNsb3VkLnN2Yy5jbHVzdGVyLmxvY2Fs
  DatabaseUser: bnh0Y2xkdXNlcg==
  DatabaseName: bmV4dGNsb3Vk
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: nextcloud-onlyoffice-secret
  namespace: nextcloud
  labels:
    app: nextcloud
    tier: onlyoffice-backend
data:
  secret: MDYwNzhmNjc5YzFlNTI1NjY3ZmUxMDliYzA1NzM1ZTg=
  header: bmV4dGNsb3Vkb25seW9mZmljZWhlYWRlcg==